sudo: false
language: node_js
node_js:
  - "10"
  - "11"
  - "13"
  - "lts/*"
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=lint
    - node_js: "lts/*"
      env: TEST_SUITE=format:ci
    - node_js: "lts/*"
      env: TEST_SUITE=gitdiff:ci
    - node_js: "lts/*"
      env: TEST_SUITE=coverage
env:
  - TEST_SUITE=test
script: npm run-script $TEST_SUITE
